# Generated by Django 3.2.10 on 2022-05-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuotesHistory',
        ),
    ]
