# Generated by Django 3.2.10 on 2022-05-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_rename_author_id_quotes_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotesToTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotes.quotes')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotes.tags')),
            ],
            options={
                'db_table': 'quotes_to_tags',
            },
        ),
    ]
