# Generated by Django 3.2.10 on 2022-05-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_auto_20220512_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='user_id',
            new_name='user',
        ),
    ]
