# Generated by Django 3.2.10 on 2022-05-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_auto_20220513_2027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuotesHistory',
        ),
    ]
