# Generated by Django 3.2.10 on 2022-05-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0002_auto_20220512_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhistory',
            old_name='user_id',
            new_name='user',
        ),
    ]
