# Generated by Django 3.2.10 on 2022-05-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quoteshistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='author_id',
            new_name='author',
        ),
    ]
