# Generated by Django 3.2.10 on 2022-05-12 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quotes.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0007_alter_authors_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quotes.models.get_file_name),
        ),
        migrations.AlterField(
            model_name='authors',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
